const language = {
    "af": "Afrikaans",
    "am": "Amárico",
    "ar": "Árabe",
    "az": "Azerbaiyano",
    "bg": "Búlgaro",
    "bn": "Bengalí",
    "bs": "Bosnio",
    "ca": "Catalán",
    "cs": "Checo",
    "cy": "Galés",
    "da": "Danés",
    "de": "Alemán",
    "el": "Griego",
    "en": "Inglés",
    "es": "Español",
    "et": "Estonio",
    "eu": "Euskera",
    "fa": "Persa",
    "fi": "Finlandés",
    "fr": "Francés",
    "gl": "Gallego",
    "he": "Hebreo",
    "hi": "Hindi",
    "hr": "Croata",
    "hu": "Húngaro",
    "hy": "Armenio",
    "id": "Indonesio",
    "ig": "Igbo",
    "is": "Islandés",
    "it": "Italiano",
    "ja": "Japonés",
    "ka": "Georgiano",
    "kk": "Kazajo",
    "km": "Jemer",
    "ko": "Coreano",
    "ky": "Kirguís",
    "la": "Latín",
    "lt": "Lituano",
    "lo": "Lao",
    "lv": "Letón",
    "mk": "Macedonio",
    "mn": "Mongol",
    "ms": "Malayo",
    "mt": "Maltés",
    "my": "Birmano",
    "ne": "Nepalí",
    "nl": "Neerlandés",
    "no": "Noruego",
    "pa": "Panyabí",
    "pl": "Polaco",
    "pt": "Portugués",
    "ro": "Rumano",
    "ru": "Ruso",
    "si": "Cingalés",
    "sk": "Eslovaco",
    "sl": "Esloveno",
    "sq": "Albanés",
    "sr": "Serbio",
    "sv": "Sueco",
    "sw": "Suajili",
    "sw-KE": "Suajili (Kenia)",
    "sw-TZ": "Suajili (Tanzania)",
    "sw-ZA": "Suajili (Sudáfrica)",
    "tg": "Tayiko",
    "th": "Tailandés",
    "tl": "Tagalo",
    "tr": "Turco",
    "uk": "Ucraniano",
    "ur": "Urdu",
    "uz": "Uzbeko",
    "vi": "Vietnamita",
    "xh": "Xhosa",
    "yo": "Yoruba",
    "zh": "Chino",
    "zh-CN": "Chino Simplificado",
    "zh-HK": "Chino Hong Kong",
    "zh-TW": "Chino Tradicional",
    "zu": "Zulu"
};
